# Generated by Django 3.0.7 on 2020-10-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Task',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('task_name', models.CharField(max_length=100)),
#                 ('completed', models.BooleanField(default=False)),
#                 ('Target_time', models.DateField()),
#             ],
#         ),
#     ]
