# Generated by Django 3.0.7 on 2020-10-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('todo', '0001_initial'),
    # ]

    # operations = [
    #     migrations.RenameField(
    #         model_name = 'task',
    #         old_name = 'Target_time',
    #         new_name = 'target'
    #     ),
    # ]
