# Generated by Django 3.0.7 on 2020-10-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201002_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=100, null=False),
        ),
    ]
