# Generated by Django 3.0.7 on 2020-10-07 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201002_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=User),
            preserve_default=False,
        ),
    ]
